; Configuración de red para llamadas
[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; Creación de la extensión 100
[100]
type=endpoint
context=default
disallow=all
allow=ulaw
auth=100
aors=100

[100]
type=auth
auth_type=userpass
password=clave_secreta_100
username=100

[100]
type=aor
max_contacts=1